### ISSUE TITLE
Allow different options in get_post_parameters

### ISSUE THREAD

**Issue by zihaoxu98** [XENONnT/appletree#186]
In [context.get_post_parameters](https://github.com/XENONnT/appletree/blob/88445b55f5e46dd8282b7a57c795a59a0fd8fb3c/appletree/context.py#L275), it returns the max-posterior parameters. Sometimes people could be interested in other definition of the "best fit", for example the marginal median etc. One can think adding an option in this function

**Comment by dachengx** [comment]
MISSION ACCOMPLISHED by https://github.com/XENONnT/appletree/pull/193
